# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_target=1.20.4
# Override minecraft_target on the command line (e.g. -Pminecraft_target=1.20.3)
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.1
loader_version=0.17.3
# Mod Properties
mod_version=3.1.1
maven_group=com.sheath
archives_base_name=Veinminer-fabric
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.97.3+1.20.4

