modLoader="javafml"
loaderVersion="[2,)"
license="All-Rights-Reserved"

[[mods]]
modId="veinminermod"
version="${version}"
displayName="Veinminer"
authors="SGTSambam"
description='''
Veinminer rebuilt with a focus on maintainability, extensibility, and cleaner internals.
'''

[[dependencies.veinminermod]]
modId="neoforge"
type="required"
versionRange="${neoforge_dependency_range}"
ordering="NONE"
side="BOTH"

[[dependencies.veinminermod]]
modId="minecraft"
type="required"
versionRange="${minecraft_dependency_range}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="veinminermod.mixins.json"
